#!/usr/bin/env bash

# .githooks/commit-msg

PATTERN_STRING="^(feat|fix|build|chore|docs|style|refactor|perf|test)(\(.*\))?!?: (.+[^.\r\n])([\r\n]+(.+[\r\n]+)+)?$"

echo "Running commit-msg hook... "

# Get commit message file
commit_msg_file=$1

if ! grep -qE "$PATTERN_STRING" "$commit_msg_file"; then
    echo "❌ Fix your commit message! ❌"
    echo "Requested pattern is `type(scope): subject`"
    exit 1
fi

echo "done ✅"