#!/bin/bash

# Custom env variables
export ELECTRON_OZONE_PLATFORM_HINT=wayland

# Homebrew
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_UPGRADE=1

# CachyOS Wayland Proton
export PROTON_ENABLE_WAYLAND=1
